package apteka;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Basian
 */
public class Apteka extends javax.swing.JFrame {

    /**
     * Creates new form blablabll
     */
    public Apteka() {
        initComponents();
    }
    String sciezka = "C:\\Users\\Basian\\Documents\\"
            + "NetBeansProjects\\Apteka\\src\\apteka\\lekarstwa.txt";

    private void dodajWiersz(ArrayList lista) throws IOException {
        DefaultTableModel model = (DefaultTableModel) jTable.getModel();
        ArrayList<String> list = lista;
        Object rowData[] = new Object[7];
        for (int i = 0; i < list.size(); i++) {
            String[] first_read = list.get(i).split(";");

            rowData[0] = first_read[0];
            rowData[1] = first_read[1];
            rowData[2] = first_read[2];
            rowData[3] = first_read[3];
            rowData[4] = first_read[4];
            rowData[5] = first_read[5];
            rowData[6] = first_read[6];
            model.addRow(rowData);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTxtSzukany = new javax.swing.JTextField();
        jZakladki = new javax.swing.JTabbedPane();
        jPanel_ID = new javax.swing.JTabbedPane();
        jBtnID = new javax.swing.JButton();
        jPanel_Nazwa = new javax.swing.JPanel();
        jBtnNazwa = new javax.swing.JButton();
        jPanel_Kategoria = new javax.swing.JTabbedPane();
        jBtnKategoria = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jBtnSklad = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jBtnPrzeciwwskazanie = new javax.swing.JButton();
        jPanelZamiennik = new javax.swing.JTabbedPane();
        jBtnZamiennik = new javax.swing.JButton();
        jBtnWyjscie = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTxtSzukany.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jTxtSzukany.setText("Wpisz szukany lek");
        jTxtSzukany.setToolTipText("");

        jBtnID.setText("Wyszukaj lek");
        jBtnID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIDActionPerformed(evt);
            }
        });
        jPanel_ID.addTab("tab1", jBtnID);

        jZakladki.addTab("ID", jPanel_ID);

        jBtnNazwa.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jBtnNazwa.setText("Wyszukaj lek");
        jBtnNazwa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnNazwaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_NazwaLayout = new javax.swing.GroupLayout(jPanel_Nazwa);
        jPanel_Nazwa.setLayout(jPanel_NazwaLayout);
        jPanel_NazwaLayout.setHorizontalGroup(
            jPanel_NazwaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_NazwaLayout.createSequentialGroup()
                .addGap(0, 882, Short.MAX_VALUE)
                .addComponent(jBtnNazwa, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel_NazwaLayout.setVerticalGroup(
            jPanel_NazwaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_NazwaLayout.createSequentialGroup()
                .addComponent(jBtnNazwa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );

        jBtnNazwa.getAccessibleContext().setAccessibleName("Wyszukaj lek ");

        jZakladki.addTab("Nazwa", jPanel_Nazwa);

        jBtnKategoria.setText("Wyszukaj lek");
        jBtnKategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnKategoriaActionPerformed(evt);
            }
        });
        jPanel_Kategoria.addTab("tab1", jBtnKategoria);

        jZakladki.addTab("Kategoria", jPanel_Kategoria);
        jPanel_Kategoria.getAccessibleContext().setAccessibleName("Kategoria");

        jBtnSklad.setText("Wyszukaj lek");
        jBtnSklad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSkladActionPerformed(evt);
            }
        });
        jTabbedPane1.addTab("tab1", jBtnSklad);

        jZakladki.addTab("Skład", jTabbedPane1);

        jBtnPrzeciwwskazanie.setText("Wyszukaj lek");
        jBtnPrzeciwwskazanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPrzeciwwskazanieActionPerformed(evt);
            }
        });
        jTabbedPane2.addTab("tab1", jBtnPrzeciwwskazanie);

        jZakladki.addTab("Przeciwwskazania", jTabbedPane2);

        jBtnZamiennik.setText("Znajdz zamiennik");
        jBtnZamiennik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnZamiennikActionPerformed(evt);
            }
        });
        jPanelZamiennik.addTab("tab1", jBtnZamiennik);

        jZakladki.addTab("Zamiennik", jPanelZamiennik);

        jBtnWyjscie.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jBtnWyjscie.setText("Wyjscie");
        jBtnWyjscie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnWyjscieActionPerformed(evt);
            }
        });

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nazwa", "Skład", "Przeciwwskazania", "Kategoria", "Cena", "Recepta"
            }
        ));
        jScrollPane2.setViewportView(jTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtSzukany)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBtnWyjscie, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jZakladki)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTxtSzukany, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jZakladki, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jBtnWyjscie, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jZakladki.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jBtnNazwaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnNazwaActionPerformed

        String szukany = jTxtSzukany.getText();
        try {
            Wczytanie w = new Wczytanie(sciezka, szukany);
            w.wyszukanie_kmp();
            dodajWiersz(w.przekazanie_elementow());

        } catch (IOException ex) {
            Logger.getLogger(Apteka.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jBtnNazwaActionPerformed

    private void jBtnWyjscieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnWyjscieActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jBtnWyjscieActionPerformed

    private void jBtnIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIDActionPerformed
        int szukany = Integer.valueOf(jTxtSzukany.getText());
        WyszukiwanieBinarne wb = new WyszukiwanieBinarne();
        try {
            dodajWiersz(wb.wyszukanieID(sciezka, szukany));
        } catch (IOException ex) {
            Logger.getLogger(Apteka.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnIDActionPerformed


    private void jBtnKategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnKategoriaActionPerformed
       String szukany = jTxtSzukany.getText();
//        try {
//            WyszukiwanieKategorie wk = new WyszukiwanieKategorie(sciezka, szukany);
//                        dodajWiersz(wk);
//        }catch (IOException ex) {
//            Logger.getLogger(Apteka.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jBtnKategoriaActionPerformed

    private void jBtnZamiennikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnZamiennikActionPerformed
       
    }//GEN-LAST:event_jBtnZamiennikActionPerformed

    private void jBtnSkladActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSkladActionPerformed
        String szukany = jTxtSzukany.getText();
        try {
            Wczytanie ww = new Wczytanie(sciezka, szukany);
            ww.porownanie_algorytm_boyer_more();
            dodajWiersz(ww.przekazanie_elementow());

        } catch (IOException ex) {
            Logger.getLogger(Apteka.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jBtnSkladActionPerformed

    private void jBtnPrzeciwwskazanieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPrzeciwwskazanieActionPerformed
        try {

            String szukany = jTxtSzukany.getText();
            Algorytm_Karpa_Rabina akr = new Algorytm_Karpa_Rabina();
            dodajWiersz(akr.wyszukaniePrzeciwwskazania(sciezka, szukany));

        } catch (IOException ex) {
            Logger.getLogger(Apteka.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnPrzeciwwskazanieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Apteka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Apteka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Apteka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Apteka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Apteka().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnID;
    private javax.swing.JButton jBtnKategoria;
    private javax.swing.JButton jBtnNazwa;
    private javax.swing.JButton jBtnPrzeciwwskazanie;
    private javax.swing.JButton jBtnSklad;
    private javax.swing.JButton jBtnWyjscie;
    private javax.swing.JButton jBtnZamiennik;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jPanelZamiennik;
    private javax.swing.JTabbedPane jPanel_ID;
    private javax.swing.JTabbedPane jPanel_Kategoria;
    private javax.swing.JPanel jPanel_Nazwa;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable;
    private javax.swing.JTextField jTxtSzukany;
    private javax.swing.JTabbedPane jZakladki;
    // End of variables declaration//GEN-END:variables

}
